[package]
name = "kupcake"
version.workspace = true
edition.workspace = true

[[bin]]
name = "kupcake"
path = "src/main.rs"

[dependencies]
kupcake-deploy.workspace = true
clap.workspace = true
anyhow.workspace = true
tokio.workspace = true
strum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rand.workspace = true
reqwest.workspace = true
serde_json.workspace = true

